name: 'Deploy slides to github pages'
description: 'Deploy slides to github pages'
inputs:
  working-directory:
    description: 'Working Directory'
    required: true
runs:
  using: composite
  steps:
  - uses: actions/setup-node@v2
    with:
      node-version: 16
  - run: npm ci
    shell: bash
    working-directory: ${{ inputs.working-directory }}
  - run: npx fusuma build
    shell: bash
    working-directory: ${{ inputs.working-directory }}
  - uses: peaceiris/actions-gh-pages@v3
    working-directory: ${{ inputs.working-directory }}
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      publish_dir: ./dist
      destination_dir: ${{ inputs.working-directory }}
