name: 'Deploy aqua/introduction-5min'
on:
  push:
    branches:
    - main
    paths:
    - aqua/introduction-5min/**
    - .github/workflows/aqua-introduction-5min.yaml
    - .github/actions/deploy/**
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/deploy
      with:
        working-directory: aqua/introduction-5min
