name: 'Deploy aqua/introduction-5min'

on:
  push:
    branches:
    - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/deploy
      with:
        working-directory: aqua/introduction-5min
