name: marp
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - marp/**
      - .github/workflows/marp.yaml
jobs:
  release-marp:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - run: npx @marp-team/marp-cli@latest -o public -I marp
      - uses: suzuki-shunsuke/gh-pages-action@6229a3f8d89389da5c234aab3b37ba51a7fee3f6 # v0.0.1
        if: github.event_name == 'push'
        with:
          app_id: ${{ secrets.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
