name: marp
on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - marp/**
      - .github/workflows/marp.yaml
jobs:
  release-marp:
    timeout-minutes: 20
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - run: npx @marp-team/marp-cli@latest -o public -I marp
      - uses: suzuki-shunsuke/gh-pages-action@9f11bf1233ad98c3cef0abdebe0e9b28f76feab7 # v0.0.2
        if: github.event_name == 'push'
        with:
          publish_dir: public
